### ISSUE TITLE
Chap 2 - getFakeMembers - jsBin - Error: XMLhttpRequest Cannot Load ...

### ISSUE THREAD

**Issue by BarDev** [MoonHighway/learning-react#5]
The link from Chapter 2 for getFakeName (http://jsbin.com/ceteja/1/edit?js,console) does not seem to work.  When I run the JSBin, I get the following error:

`XMLHttpRequest cannot load http://api.randomuser.me/?nat=US&results=5. Redirect from 'http://api.randomuser.me/?nat=US&results=5' to 'https://api.randomuser.me/?nat=US&results=5' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://null.jsbin.com' is therefore not allowed access.`

**Comment by eveporcello** [comment]
Thanks for passing this along! We've fixed this in the final version of the book but needed to resolve here too. The fetch from the API previously worked as an http. Now it needs https. 

Updated sample: http://jsbin.com/pupojik/1/edit?js,console 

I fixed in the link list on the Chapter 2 page also.
