### ISSUE TITLE
backpacking meals error message

### ISSUE THREAD

**Issue by cyuno** [MoonHighway/learning-react#6]
The following code:
var morning = {
  breakfast: "oatmeal",
  lunch: "peanut butter and jelly"
}

var dinner = "mac and cheese"

var backpackingMeals = {
  ...morning,
  dinner
}

console.log(backpackingMeals)

gives me the following error in chrome developer tools:

Uncaught SyntaxError: Unexpected token ...

**Comment by vlad-bezden** [comment]
'...' spread operator, and at this point it's part of ES2015 for arrays, but not for objects. There is an proposal to add it to objects '[Rest/Spread Properties for ECMAScript](https://github.com/tc39/proposal-object-rest-spread)', and right now it is a stage 3 proposal of ECMAScript.

In order to use it you also have install babel [preset stage 0](https://babeljs.io/docs/plugins/preset-stage-0/), that includes stage 1, 2, and 3

`npm install --save-dev babel-preset-stage-0`

after you install it, you will have to transpile your code using babel to ES2015 code, so your browser can understand that code. Take a look at chapter 5 of the book. It has more information how to use it.

Hope this helps

**Comment by eveporcello** [comment]
Thanks for the question and for reading, @cyuno. 

@vlad-bezden is absolutely right - your browser will (most likely) support the array spread operator but not object spread. Installing babel-preset-stage-0 will fix this.

If you'd like to see a version without the whole npm setup, I the sample into a JSBin [here](http://jsbin.com/catali/1/edit?js,console) that transpiles with Babel.

Feel free to reach out via email (or here) if other questions come up.
