### ISSUE TITLE
Why did you add semicolons at end of the statement in the second edition?

### ISSUE THREAD

**Issue by yangxyo** [MoonHighway/learning-react#62]
I love your books.
In the first edition, you omitted the semicolons, but why did you add semicolons at end of the statement in the second edition?

**Comment by MoonTahoe** [comment]
`prettier`. We stopped the semicolon fight in favor of perttier default formatting. Look, I don't like to use semicolons, but it is way easier to teach if I just accept the default formatting of prettier because all students need to do is setup prettier and our code will look exactly the same. 

In my own private, product, non teaching code... prettier is configured for no semicolons.
