### ISSUE TITLE
Chapter 8 - Where is this SearchForm component?

### ISSUE THREAD

**Issue by Jay-study-nildana** [MoonHighway/learning-react#68]
Folks, 

I have no idea where is this SearchForm. The textbook keeps using it throughout the demo. I have checked the current repo and you dont use it in any of your sandboxes. 

So, where this this SearchForm component? 

Or, are you suggesting that we build it using what we have learnt till now. 

This is the sentence 'Assuming we have a SearchForm component ready to collect search strings from the user'. Why would you assume that? 

I dont get it.

**Comment by MoonTahoe** [comment]
What page?

**Comment by Jay-study-nildana** [comment]
Hello.

I am an online learning subscriber. I dont see any page numbers here.

`Chapter 8 - Incorporating Data`

Right after you describe the following line, 

`function GitHubUser({ login }) {`

you use this line. 

`Although the component now has less logic, it still handles all three states. Assuming we have a SearchForm component ready`

But nowhere in the chapter or in this github repository sandboxes, have you provided the form code. A lot of things in the chapter depend on this SearchForm, making this a bit of roadblock. Please help.

**Comment by MoonTahoe** [comment]
It seems like it didn't make it:

"Assuming we have a SearchForm component ready to collect search strings from the user, we can add the GitHubUser component to our main App component:"

I guess we choose the phrase "Assuming we have a SearchForm"... cause we don't.

I'm not really sure how we missed that in our samples. In the book, we assume that you can code one by Chapter 8 because it is just a text field to collect the Github user's name. But it should be in the samples... thanks.

If you want to use one:

```javascript
export default function SearchForm({ value="", onSearch=f=>f }) {
  return (
    <input value={value} onChange={e => onSearch(e.target.value) />
  );
}
```
